/**
 * @fileOverview Data lengkap 114 Surat Al-Quran untuk fitur Talaqqi dan Tahfidz.
 */

export interface Surah {
  number: number;
  name: string;
  arabicName: string;
  revelationType: string;
  totalVerses: number;
}

export const ALL_SURAHS: Surah[] = [
  { number: 1, name: "Al-Fatihah", arabicName: "الفاتحة", revelationType: "Mekah", totalVerses: 7 },
  { number: 2, name: "Al-Baqarah", arabicName: "البقرة", revelationType: "Madinah", totalVerses: 286 },
  { number: 3, name: "Ali 'Imran", arabicName: "آل عمران", revelationType: "Madinah", totalVerses: 200 },
  { number: 4, name: "An-Nisa'", arabicName: "النساء", revelationType: "Madinah", totalVerses: 176 },
  { number: 5, name: "Al-Ma'idah", arabicName: "المائدة", revelationType: "Madinah", totalVerses: 120 },
  { number: 6, name: "Al-An'am", arabicName: "الأنعام", revelationType: "Mekah", totalVerses: 165 },
  { number: 7, name: "Al-A'raf", arabicName: "الأعراف", revelationType: "Mekah", totalVerses: 206 },
  { number: 8, name: "Al-Anfal", arabicName: "الأنفال", revelationType: "Madinah", totalVerses: 75 },
  { number: 9, name: "At-Tawbah", arabicName: "التوبة", revelationType: "Madinah", totalVerses: 129 },
  { number: 10, name: "Yunus", arabicName: "يونس", revelationType: "Mekah", totalVerses: 109 },
  { number: 11, name: "Hud", arabicName: "هود", revelationType: "Mekah", totalVerses: 123 },
  { number: 12, name: "Yusuf", arabicName: "يوسف", revelationType: "Mekah", totalVerses: 111 },
  { number: 13, name: "Ar-Ra'd", arabicName: "الرعد", revelationType: "Madinah", totalVerses: 43 },
  { number: 14, name: "Ibrahim", arabicName: "إبراهيم", revelationType: "Mekah", totalVerses: 52 },
  { number: 15, name: "Al-Hijr", arabicName: "الحجر", revelationType: "Mekah", totalVerses: 99 },
  { number: 16, name: "An-Nahl", arabicName: "النحل", revelationType: "Mekah", totalVerses: 128 },
  { number: 17, name: "Al-Isra'", arabicName: "الإسراء", revelationType: "Mekah", totalVerses: 111 },
  { number: 18, name: "Al-Kahf", arabicName: "الكهف", revelationType: "Mekah", totalVerses: 110 },
  { number: 19, name: "Maryam", arabicName: "مريم", revelationType: "Mekah", totalVerses: 98 },
  { number: 20, name: "Ta-Ha", arabicName: "طه", revelationType: "Mekah", totalVerses: 135 },
  { number: 21, name: "Al-Anbiya'", arabicName: "الأنبياء", revelationType: "Mekah", totalVerses: 112 },
  { number: 22, name: "Al-Hajj", arabicName: "الحج", revelationType: "Madinah", totalVerses: 78 },
  { number: 23, name: "Al-Mu'minun", arabicName: "المؤمنون", revelationType: "Mekah", totalVerses: 118 },
  { number: 24, name: "An-Nur", arabicName: "النور", revelationType: "Madinah", totalVerses: 64 },
  { number: 25, name: "Al-Furqan", arabicName: "الفرقان", revelationType: "Mekah", totalVerses: 77 },
  { number: 26, name: "Asy-Syu'ara'", arabicName: "الشعراء", revelationType: "Mekah", totalVerses: 227 },
  { number: 27, name: "An-Naml", arabicName: "النمل", revelationType: "Mekah", totalVerses: 93 },
  { number: 28, name: "Al-Qasas", arabicName: "القصص", revelationType: "Mekah", totalVerses: 88 },
  { number: 29, name: "Al-'Ankabut", arabicName: "العنكبوت", revelationType: "Mekah", totalVerses: 69 },
  { number: 30, name: "Ar-Rum", arabicName: "الروم", revelationType: "Mekah", totalVerses: 60 },
  { number: 31, name: "Luqman", arabicName: "لقمان", revelationType: "Mekah", totalVerses: 34 },
  { number: 32, name: "As-Sajdah", arabicName: "السجدة", revelationType: "Mekah", totalVerses: 30 },
  { number: 33, name: "Al-Ahzab", arabicName: "الأحزاب", revelationType: "Madinah", totalVerses: 73 },
  { number: 34, name: "Saba'", arabicName: "سبأ", revelationType: "Mekah", totalVerses: 54 },
  { number: 35, name: "Fatir", arabicName: "فاطر", revelationType: "Mekah", totalVerses: 45 },
  { number: 36, name: "Ya-Sin", arabicName: "يس", revelationType: "Mekah", totalVerses: 83 },
  { number: 37, name: "As-Saffat", arabicName: "الصافات", revelationType: "Mekah", totalVerses: 182 },
  { number: 38, name: "Sad", arabicName: "ص", revelationType: "Mekah", totalVerses: 88 },
  { number: 39, name: "Az-Zumar", arabicName: "الزمر", revelationType: "Mekah", totalVerses: 75 },
  { number: 40, name: "Ghafir", arabicName: "غافر", revelationType: "Mekah", totalVerses: 85 },
  { number: 41, name: "Fussilat", arabicName: "فصلت", revelationType: "Mekah", totalVerses: 54 },
  { number: 42, name: "Asy-Syura", arabicName: "الشورى", revelationType: "Mekah", totalVerses: 53 },
  { number: 43, name: "Az-Zukhruf", arabicName: "الزخرف", revelationType: "Mekah", totalVerses: 89 },
  { number: 44, name: "Ad-Dukhan", arabicName: "الدخان", revelationType: "Mekah", totalVerses: 59 },
  { number: 45, name: "Al-Jathiyah", arabicName: "الجاثية", revelationType: "Mekah", totalVerses: 37 },
  { number: 46, name: "Al-Ahqaf", arabicName: "الأحقاف", revelationType: "Mekah", totalVerses: 35 },
  { number: 47, name: "Muhammad", arabicName: "محمد", revelationType: "Madinah", totalVerses: 38 },
  { number: 48, name: "Al-Fath", arabicName: "الفتح", revelationType: "Madinah", totalVerses: 29 },
  { number: 49, name: "Al-Hujurat", arabicName: "الحجرات", revelationType: "Madinah", totalVerses: 18 },
  { number: 50, name: "Qaf", arabicName: "ق", revelationType: "Mekah", totalVerses: 45 },
  { number: 51, name: "Ad-Dhariyat", arabicName: "الذاريات", revelationType: "Mekah", totalVerses: 60 },
  { number: 52, name: "At-Tur", arabicName: "الطور", revelationType: "Mekah", totalVerses: 49 },
  { number: 53, name: "An-Najm", arabicName: "النجم", revelationType: "Mekah", totalVerses: 62 },
  { number: 54, name: "Al-Qamar", arabicName: "القمر", revelationType: "Mekah", totalVerses: 55 },
  { number: 55, name: "Ar-Rahman", arabicName: "الرحمن", revelationType: "Madinah", totalVerses: 78 },
  { number: 56, name: "Al-Waqi'ah", arabicName: "الواقعة", revelationType: "Mekah", totalVerses: 96 },
  { number: 57, name: "Al-Hadid", arabicName: "الحديد", revelationType: "Madinah", totalVerses: 29 },
  { number: 58, name: "Al-Mujadilah", arabicName: "المجادلة", revelationType: "Madinah", totalVerses: 22 },
  { number: 59, name: "Al-Hasyr", arabicName: "الحشر", revelationType: "Madinah", totalVerses: 24 },
  { number: 60, name: "Al-Mumtahanah", arabicName: "الممتحنة", revelationType: "Madinah", totalVerses: 13 },
  { number: 61, name: "As-Saff", arabicName: "الصف", revelationType: "Madinah", totalVerses: 14 },
  { number: 62, name: "Al-Jumu'ah", arabicName: "الجمعة", revelationType: "Madinah", totalVerses: 11 },
  { number: 63, name: "Al-Munafiqun", arabicName: "المنافقون", revelationType: "Madinah", totalVerses: 11 },
  { number: 64, name: "At-Taghabun", arabicName: "التغابن", revelationType: "Madinah", totalVerses: 18 },
  { number: 65, name: "At-Talaq", arabicName: "الطلاق", revelationType: "Madinah", totalVerses: 12 },
  { number: 66, name: "At-Tahrim", arabicName: "التحريم", revelationType: "Madinah", totalVerses: 12 },
  { number: 67, name: "Al-Mulk", arabicName: "الملك", revelationType: "Mekah", totalVerses: 30 },
  { number: 68, name: "Al-Qalam", arabicName: "القلم", revelationType: "Mekah", totalVerses: 52 },
  { number: 69, name: "Al-Haqqah", arabicName: "الحاقة", revelationType: "Mekah", totalVerses: 52 },
  { number: 70, name: "Al-Ma'arij", arabicName: "المعارج", revelationType: "Mekah", totalVerses: 44 },
  { number: 71, name: "Nuh", arabicName: "نوح", revelationType: "Mekah", totalVerses: 28 },
  { number: 72, name: "Al-Jinn", arabicName: "الجن", revelationType: "Mekah", totalVerses: 28 },
  { number: 73, name: "Al-Muzzammil", arabicName: "المزمل", revelationType: "Mekah", totalVerses: 20 },
  { number: 74, name: "Al-Muddaththir", arabicName: "المدثر", revelationType: "Mekah", totalVerses: 56 },
  { number: 75, name: "Al-Qiyamah", arabicName: "القيامة", revelationType: "Mekah", totalVerses: 40 },
  { number: 76, name: "Al-Insan", arabicName: "الإنسان", revelationType: "Madinah", totalVerses: 31 },
  { number: 77, name: "Al-Mursalat", arabicName: "المرسلات", revelationType: "Mekah", totalVerses: 50 },
  { number: 78, name: "An-Naba'", arabicName: "النبأ", revelationType: "Mekah", totalVerses: 40 },
  { number: 79, name: "An-Nazi'at", arabicName: "النازعات", revelationType: "Mekah", totalVerses: 46 },
  { number: 80, name: "'Abasa", arabicName: "عبس", revelationType: "Mekah", totalVerses: 42 },
  { number: 81, name: "At-Takwir", arabicName: "التكوير", revelationType: "Mekah", totalVerses: 29 },
  { number: 82, name: "Al-Infitar", arabicName: "الانفطار", revelationType: "Mekah", totalVerses: 19 },
  { number: 83, name: "Al-Mutaffifin", arabicName: "المطففين", revelationType: "Mekah", totalVerses: 36 },
  { number: 84, name: "Al-Insyiqaq", arabicName: "الانشقاق", revelationType: "Mekah", totalVerses: 25 },
  { number: 85, name: "Al-Buruj", arabicName: "البروج", revelationType: "Mekah", totalVerses: 22 },
  { number: 86, name: "At-Tariq", arabicName: "الطارق", revelationType: "Mekah", totalVerses: 17 },
  { number: 87, name: "Al-A'la", arabicName: "الأعلى", revelationType: "Mekah", totalVerses: 19 },
  { number: 88, name: "Al-Ghasyiyah", arabicName: "الغاشية", revelationType: "Mekah", totalVerses: 26 },
  { number: 89, name: "Al-Fajr", arabicName: "الفجر", revelationType: "Mekah", totalVerses: 30 },
  { number: 90, name: "Al-Balad", arabicName: "البلد", revelationType: "Mekah", totalVerses: 20 },
  { number: 91, name: "Asy-Syams", arabicName: "الشمس", revelationType: "Mekah", totalVerses: 15 },
  { number: 92, name: "Al-Layl", arabicName: "الليل", revelationType: "Mekah", totalVerses: 21 },
  { number: 93, name: "Ad-Duha", arabicName: "الضحى", revelationType: "Mekah", totalVerses: 11 },
  { number: 94, name: "Asy-Syarh", arabicName: "الشرح", revelationType: "Mekah", totalVerses: 8 },
  { number: 95, name: "At-Tin", arabicName: "التين", revelationType: "Mekah", totalVerses: 8 },
  { number: 96, name: "Al-'Alaq", arabicName: "العلق", revelationType: "Mekah", totalVerses: 19 },
  { number: 97, name: "Al-Qadr", arabicName: "القدر", revelationType: "Mekah", totalVerses: 5 },
  { number: 98, name: "Al-Bayyinah", arabicName: "البينة", revelationType: "Madinah", totalVerses: 8 },
  { number: 99, name: "Az-Zalzalah", arabicName: "الزلزلة", revelationType: "Madinah", totalVerses: 8 },
  { number: 100, name: "Al-'Adiyat", arabicName: "العاديات", revelationType: "Mekah", totalVerses: 11 },
  { number: 101, name: "Al-Qari'ah", arabicName: "القارعة", revelationType: "Mekah", totalVerses: 11 },
  { number: 102, name: "At-Takathur", arabicName: "التكاثر", revelationType: "Mekah", totalVerses: 8 },
  { number: 103, name: "Al-'Asr", arabicName: "العصر", revelationType: "Mekah", totalVerses: 3 },
  { number: 104, name: "Al-Humazah", arabicName: "الهمزة", revelationType: "Mekah", totalVerses: 9 },
  { number: 105, name: "Al-Fil", arabicName: "الفيل", revelationType: "Mekah", totalVerses: 5 },
  { number: 106, name: "Quraysy", arabicName: "قريش", revelationType: "Mekah", totalVerses: 4 },
  { number: 107, name: "Al-Ma'un", arabicName: "الماعون", revelationType: "Mekah", totalVerses: 7 },
  { number: 108, name: "Al-Kawthar", arabicName: "الكوثر", revelationType: "Mekah", totalVerses: 3 },
  { number: 109, name: "Al-Kafirun", arabicName: "الكافرون", revelationType: "Mekah", totalVerses: 6 },
  { number: 110, name: "An-Nasr", arabicName: "النصر", revelationType: "Madinah", totalVerses: 3 },
  { number: 111, name: "Al-Masad", arabicName: "المسد", revelationType: "Mekah", totalVerses: 5 },
  { number: 112, name: "Al-Ikhlas", arabicName: "الإخلاص", revelationType: "Mekah", totalVerses: 4 },
  { number: 113, name: "Al-Falaq", arabicName: "الفلق", revelationType: "Mekah", totalVerses: 5 },
  { number: 114, name: "An-Nas", arabicName: "الناس", revelationType: "Mekah", totalVerses: 6 },
];
